### ISSUE TITLE
wemo stops responding after an hour or so

### ISSUE THREAD

**Issue by clarkworld** [rudders/homebridge-platform-wemo#70] opened 2016-11-12 05:34 UTC
Homebridge continues to work with other devices but the wemo platforms stops responding. I set the wemo devices to static IPs which helped a bit but after no consistent set of time the device stops working until I reboot homebridge, sometimes multiple times.

The wemo device still works from IFTTT and the wemo app. The IP hasn't changed and the homebridge log shows no errors but homekit doesn't receive status updates and loses access to control the light switch. 

Any suggestions?

**Comment by devbobo** [comment] 2016-11-14 07:07
I believe this is a duplicate of https://github.com/rudders/homebridge-platform-wemo/issues/33.

Please read through the comments on that issue and reopen if you don't agree

**Closed by devbobo** 2016-11-14 07:07 UTC

**Comment by clarkworld** [comment] 2016-11-14 15:13
It is not a state issue but it may be related. In the Home app on my phone the device is listed as not available.

**Comment by devbobo** [comment] 2016-11-14 22:09
if you read the comments towards the bottom, people are talking about it stoping responding after a period of time. I believe that this is more related to how and on what system it's being run, rather than a code issue.

Numerous people who were having similar issues to you, migrated to using a RPi and the problem went away completely.
