### ISSUE TITLE
Homebridge Not Always Recognizing State Changes

### ISSUE THREAD

**Issue by erfinb** [rudders/homebridge-platform-wemo#33] opened 2016-02-29 17:16 UTC
My homebridge has developed an interesting new habit where it thinks lights are in one state when they are indeed in another.  For example, let's say the light is on and is being reported that way in the WeMo app, and homebridge thinks it is off I have to ask for homebridge to turn the light off and then ask it to turn the light back on again before the status will report correctly.  This is very strange and I'm not sure what is going on. If I restart homebridge then I am usually back in business.  Is there a way perhaps to have homebridge restart itself every thirty minutes or hour to minimize this issue? (I'm using a Mac to run homebridge.)

**Comment by tekuonline** [comment] 2016-02-29 17:23
This stared to happen to me aswell few days ago. I think the wemo status is not updated to the HK correctly. When I say "Siri, turn off my kitchen light", siri replies "ok, the kitchen light is  turned off" but the light actually does not turn off. But if I say "siri turn on my kitchen light", and then "siri turn off my kitchen light", the lights are turned off.

**Comment by erfinb** [comment] 2016-02-29 17:51
That is the exact issue I am having!  Any ideas on how we can fix this? :-)

**Comment by erfinb** [comment] 2016-03-04 04:24
Tekuonline, are you still experiencing these issues as well? Or have you found a solution?

**Comment by uchuujin** [comment] 2016-03-09 17:10
This problem for me has more or less made me stop trying to use Siri/HomeKit... It works about half the time, whereas the standard Wemo app works every time.

It's hard to say in which layer the problem lies, but it's clear that homebridge does not have a reliable status for devices and/or that commands are not getting through.  As @tekuonline has said, Siri will say she has turned a light on or off yet nothing changes.  My HomeKit app Eve also reports inaccurate status.

Even more annoying, when tell asking Siri to do something, the response very often "Sorry, Boss, I couldn't get a response from any of your devices".  Yet.. when then giving the order "Turn off everything", everything will indeed be switched off.

To be honest, I've gone back to using the Wemo app and QuickSwitch, which has a very nice and readily available interface in the lock screen.

**Comment by rudders** [comment] 2016-03-09 17:23
I've been travelling on business and not able to dig into this to see where the issue is - there is also a new version of Homebridge that manage these state changes more elegantly although ios9.3 beta experience for me is suggesting we have some more work to do. I'll take a fresh look at it this week when I get back to Australia from the UK. Have you checked out the slack channels to see if anyone has any good thoughts on these issues?

**Comment by erfinb** [comment] 2016-03-09 17:26
Thank you @rudders ! 😃

**Comment by uchuujin** [comment] 2016-03-09 17:49
Interesting... I'm also running the beta 9.3.  I did upgrade just a few minutes ago to the new version of Homebridge.

**Comment by erfinb** [comment] 2016-03-09 17:50
I've been running the beta and updated a few days ago to the new HomeBridge version unless another version has released recently. :-)

**Comment by tekuonline** [comment] 2016-03-09 22:02
@erfinb @rudders running Latest homebridge and latest ios beta and i am still experiencing these issues.

**Comment by erfinb** [comment] 2016-03-13 02:01
Greeting all, wondering if we had any status on this 🙂 as always I appreciate all of the work you do!!!

**Comment by rudders** [comment] 2016-03-14 09:05
I"ve been away on business for a couple of weeks - just back and into my home timezone now - I'll be taking a look at these issues this week.

**Comment by erfinb** [comment] 2016-03-31 03:39
Hey @rudders I'm sorry to bother you, but I was wondering if you had any feedback on this?

**Comment by erfinb** [comment] 2016-04-05 03:44
Is there anything I can do or provide to help in figuring out what is going on with this? 🙂

**Comment by devbobo** [comment] 2016-04-05 05:25
@erfinb one of the problems with the underlying client that is used for the `WeMo` communications is it replies on `broadcast` messages for status updates. So right now, the WeMo client only `sees` the broadcast messages when the status of a light (for example) is toggled. The WeMo client currently hasn't implemented being able to specifically ask for the status of a single bulb. I believe that implementing these in both the homebridge platform and the wemo client would go a long way to improving the stability.

**Comment by devbobo** [comment] 2016-04-05 05:30
Actually, after checking out the `wemo-client` code, it seems that this `shouldn't` be a problem for WeMo bulbs...but for other WeMo devices.

**Comment by rlmcguire** [comment] 2016-06-17 21:00
I am having this exact same issue. Just wondering if any progress has been made since the last posts? Thanks!

**Comment by thatskiff** [comment] 2016-08-18 10:34
Hi @devbobo and @rudders I'm having the exact same issue as described above. The status as reported to homekit by homebridge is not being updated when a Wemo Light Switch is turned on or off physically or via the Wemo app. So when a light is on, Homekit still things it is off. I have to ask Siri to turn the light on (when it actually already is on) and only then will asking Siri to turn the Light off actually work. 

Any fixes or suggestions on how to overcome this? 
Thanks, Jordan

**Comment by tmur11** [comment] 2016-08-19 21:34
@thatskiff I had the same issue with manual toggles of wemo's not updating their status to homekit. The issue in my case was indeed the amount of memory that was available on the device which was running homebridge. I switched from running homebridge on a raspberry pi A+ to a Mac and all has been resolved. Its been up for weeks with zero issues with status updates. Initially the Pi would perform status updates fine but deteriorate after a few days of running.

**Comment by driskell** [comment] 2016-08-21 12:06
This could be related to `cb` problems - the setOn stuff returns before it finishes setting things on, so could result in things not updating correctly too? Just a guess. About to buy a Wemo plug so I can test and PR maybe 😃

**Comment by driskell** [comment] 2016-08-21 14:50
Might be worth testing https://github.com/rudders/homebridge-platform-wemo/pull/53 ? It fixes the callback things.

**Comment by tmur11** [comment] 2016-08-21 19:05
@driskell would this fix apply to wemo switches or only to the wemo bulbs?

**Comment by driskell** [comment] 2016-08-24 06:16
@tmur11 Only bulbs I think.

**Comment by rlmcguire** [comment] 2016-08-27 20:35
@tmur11 Thank you! It turns out that lack of RAM seems to be the issue. I was using an old Mac mini with 2GB of RAM for the server. I just upgraded it to 8GB and it solved the problem! Now, the status always updates instantly.

**Comment by thatskiff** [comment] 2016-08-28 00:55
@tmur11 I'm running on an rpi3 so picking RAM could be my issue as well. Exactly the same thing happens, after a reboot it runs fine and then deteriorates. It always knows the last status the switch was set to from home kit, but if a state change occurs due to physically pressing the switch, or using the wemo app or controlling via Alexa then homekit does not detect the state change. 
Would be great if there was a way to fix this without needing to ditch the rpi3 as I specifically purchased it to play with homebridge.

**Comment by rlmcguire** [comment] 2016-08-28 01:01
@thatskiff That was my exact issue as well. I looked at my Activity Monitor and the homebridge process in terminal was taking up 620MB of RAM alone.

**Comment by driskell** [comment] 2016-08-28 08:43
Short of RAM seems really odd, especially as Node has very low limits anyway in earlier versions and if I remember would fatal crash if it ran out. Was there nothing in the logs about it? When you reproduce the issue in the Pi do the logs look different to when it is working?

@devbobo is right in that ideally the platform needs to be able to query status so at least when any broadcast are missed it can still update (like when pulling down refresh in Eve or opening Home app).

Timescales for this be useful too. How many devices were connected and how long before it deteriorated? Node version be useful too.

**Comment by driskell** [comment] 2016-08-28 08:45
A definition if deterioration would be useful too. Does it begin to be intermittent and then eventually never update status? Or is it just a case of temperamental behaviour?

**Comment by tmur11** [comment] 2016-08-31 00:25
@driskell in my case I have 7 wemo devices (wishing I could get my maker to work on wemo-platform). On the PI which was an A+ I could get about 24 hours out of it before the devices would stop updating completely. It did seem to be more of an on/off type symptom as opposed to a deteriorating on,

I also just had my first lock up while running it on a mac, I was up for around two weeks before the manual status stopped updating. Unfortunately I did not check the homebridge process usage myself. Anything I should check specifically when this occurs again?

**Comment by rlmcguire** [comment] 2016-10-02 02:45
After updating to 1.0.2, now the new iOS 10 Home app will not change the state of the on/off until I close the app and reopen it. And, after several hours of Homebridge running, the status will not update at all.

**Comment by devbobo** [comment] 2016-10-02 03:05
Specifically, which WeMo devices ? Are you running the latest version of homebridge ?

**Comment by rlmcguire** [comment] 2016-10-02 03:17
They are all WeMo Light Switches. I'm on 0.4.6.

**Comment by devbobo** [comment] 2016-10-02 09:09
@rlmcguire hmm, ok...they are the only devices I don't have. Hopefully, I'll have a chance to pick one up this week and work out what's up there.

**Comment by rlmcguire** [comment] 2016-10-02 22:50
Ok, great! Thanks for all of your hard work!

**Comment by devbobo** [comment] 2016-10-04 02:53
@rlmcguire please try out `1.1.0`

**Comment by rlmcguire** [comment] 2016-10-04 03:13
It seems to be the same on 1.1.0. As soon as I press the physical light switch, the macOS terminal updates with the status of the switch. But, it doesn't seem to push it to the iPhone until I press the home button and reopen the Home app. However, if I use Siri to say "turn off/turn on" the switch, it will still do it, even though the Home app hasn't updated with the correct status.

**Comment by rlmcguire** [comment] 2016-10-04 03:20
Also, something else I've noticed. If I create an automation on the Home app that says, for example, If Ceiling light turns on, turn on Bathroom light, it doesn't seem to work, even if I turn on the Ceiling light from the Home app.

**Comment by devbobo** [comment] 2016-10-04 03:23
@rlmcguire are you able to progressively rollback through the recent releases to see if it starts working again ?

**Comment by rlmcguire** [comment] 2016-10-04 03:28
I know it was working okay on 0.6.9, the only problem I had with that release was after a few hours of running, the status would just stop updating period, until I restarted HomeBridge.

**Comment by devbobo** [comment] 2016-10-04 05:38
@rlmcguire ok, I've fixed my dumb...hopefully this time (`version 1.1.1`)

**Comment by rlmcguire** [comment] 2016-10-04 15:28
Hey, it's working now! I'll let you know how the updating holds up in a few hours. Thank you!!

**Comment by rlmcguire** [comment] 2016-10-05 01:09
After about 10-11 hours, it seems to do that same thing it did on 0.6.9. The Terminal on OS X doesn't receive the status updates if I toggle the physical light switch, and it doesn't send it to the Home app. I could just set a script to relaunch Homebridge every 9 hours or so. Let me know if you need any more info.

**Comment by rlmcguire** [comment] 2016-10-05 01:38
It seems like there could be some kind of memory limit on the program. If I look at my Activity Monitor, the "kernel_task" (homebridge) won't go over 666.4 MB of memory. (I have 8GB on my computer) Maybe there is some way to dump old info stored in memory? (I obviously don't exactly know what I'm talking about)

**Comment by devbobo** [comment] 2016-10-05 01:40
@rlmcguire i'd be starting to look at your setup. My RPi has been running for 16 hours with no problems at all, everything is still communicating. Are you just running Homebridge manually in terminal ? Or some other method ?

**Comment by rlmcguire** [comment] 2016-10-05 01:43
I've just been running manually in the Terminal. I have a Raspberry Pi that I could install Homebridge on as well

**Comment by rlmcguire** [comment] 2016-10-05 22:24
Thanks for the advice about that as well. I've been running Homebridge on my Raspberry Pi for about 20 hours now with no issues!

**Comment by kenderson** [comment] 2016-10-06 13:21
@rlmcguire or @devbobo - I have similar issues on this side. I have a couple RPis, but I've never actually done anything with them. Are there any good step-by-step instructions that you guys can point me to that would help walk me through the set-up, connection, and remote management of an application like this? Thank you both!

**Comment by rlmcguire** [comment] 2016-10-06 13:30
I just followed these instructions step by step and it works perfectly 
https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

**Comment by joein3d** [comment] 2016-10-15 11:27
@devbobo @rlmcguire  I've been seeing the same issue with state changes made outside of HomeKit no longer propagating after awhile. It's actually why I started submitting pull requests - to mitigate and hopefully eventually fix the problem. It seems the same issue happens even just running wemo-client independently, so I would guess at least part of the issue is there (or with the switches themselves).

Did switching to RPi fix the issue for both of you?

**Comment by rlmcguire** [comment] 2016-10-15 14:56
@joein3d Yes, it did. I've been running for about 10 days straight and it's still working perfectly

**Comment by joein3d** [comment] 2016-10-17 11:10
@rlmcguire are you running node 4.6.0 or 6.8.1?

**Comment by tmur11** [comment] 2016-10-17 23:39
@joein3d @rlmcguire I've been running homebridge on my mac on a wired connection for 15 days with no issues with updates. Though I had manual wemo toggle update issues with my PI which seemed related to memory resources.

**Comment by joein3d** [comment] 2016-10-18 01:16
@tmur11 what versions of OS X & node are you running?

Here's the setup I had issues with:

```
Late 2009 Mac Mini running OS X 10.11.6
Node 4.6.0 and 6.81 (tried both)
homebridge@0.4.6
homebridge-platform-wemo@1.1.5
wemo-client@0.11.1
Wired Ethernet to Netgear R6400
4 WeMo Light Switches (the in-wall model, not the plug-in version) with static IPs from the router
```

**Comment by tmur11** [comment] 2016-11-15 00:41
@joein3d @devbobo been MIA for the past while, manual on/off toggle updates had been running alright up until tonight for me. I'd say that was approximately a month or so, homebridge memory usage was around 53mb which on a fresh start homebridge uses about 42mb.

I'm moved to running my setup on a virtualized mac which I had previous installed on a RPi B first gen then RPi A+ both would only last about a week before manual toggles would stop responding (although those were back when it was the older version of this plugin). I now run macOS Sierra with 4 x 3.17Ghz CPU and 4GB of RAM, node v6.7, homeridge@0.4.9, homebridge-platform-wemo@1.1.5, wemo-client@0.11.1

I just updated to the latest homebridge build and will see if that makes any difference. It's too bad we can't pinpoint the issue, one fella was indicating he though it may be related to the wemo-client itself and not necessarily the homebridge-platform-wemo plugin.

I mean my machine has tons of resources so there should be no reason it should stop working over time.  I'm sure there's many other factors at play like how often the connection to the wemo devices is interrupted and re-established. I tried for fun to see if i could run the homebridge memory usage up/kill the manual status updates from working by spamming the crap out of the wemo switch/home app toggle but no luck although I can see the RAM usage increasing slightly as i was spamming the toggles and it never seem to release the memory and return to around 42mb.

**Comment by mmaxwell5** [comment] 2016-11-16 18:08
I am running the latest version of Homebridge and wemo-platform plugin.  After about 10 - 30 min, the state changes are no longer recognized.  I am running homebridge on a dedicated Linux box (Ubuntu 14.04.5 LTS) with 2 GB of RAM and 1 core of a Intel Xeon processor (Virtualized).  I had the same result when I was running my home bridge server on a raspberry pi as well.  All devices are on the same network.  

Any information I can provide to help remove this I am happy to.  Thank you for any hallo anyone is able to provide.

**Comment by mmaxwell5** [comment] 2016-12-14 02:53
Wanted to give an update.  While troubleshooting this issue, I have been able to further pin point when the states stop getting recognized for me.  I am running my homebridge instance in a dedicated Linux box (Ubuntu 14.04.5 LTS) with 2 GB of RAM and 1 core of a Intel Xeon processor (Virtualized).  I have all my software up to date (including my homebridge and homebridge plugins).  

When I restart my homebridge service and wait a few minutes before changing the Wemo switch state either via Homekit or the physical button, all my Wemo switches (about 8) states are now recognized and continue to to work (about 3 weeks now).  

If I restart my homebridge service and toggle a Wemo switch from either HomeKit or the physical switch, the states are not recognized properly

I have been able to replicate this consistently.  It seems like homebridge needs a little time to correctly find and register the Wemo client devices.  

Hope this helps everyone.  Happy to provide any other information.

**Comment by shawnie-boy** [comment] 2016-12-28 17:39
I have the same problem. After some time homebridge stops recognizing state changes. It doesn't do the get command. I also find that when I reload homebridge I have to reset my wemo devices at same time otherwise it doesn't show up.

**Comment by jaggles** [comment] 2017-01-05 03:33
Same thing is happening to me. 

If I uninstall (npm uninstall -g homebridge-platform-wemo), delete the ".homebridge/persist" and ".homebridge/accessories", reinstall (npm install -g homebridge-platform-wemo), launch HomeBridge again (node homebridge), and then re-add the HomeBridge device to the Home app, then my WeMo plug and motion sensor show up. If I restart HomeBridge, they are no longer recognized in the Home app.

In case it helps, I'm on Windows 10 using the latest version of HomeBridge and this plugin, and using iOS 10.2 on an iPhone 7.

**Comment by jngothia** [comment] 2017-01-09 19:05
Having the same issue.  WeMo device statuses are not in sync with HomeKit.  If I turn a switch on manually, I then have to ask Siri to turn on the switch before I can then ask her to turn it off, otherwise she just seems to assume the switch is still off and tells me the device is off even though it's on.  Running Homebridge on a Hackintosh.

**Comment by jaggles** [comment] 2017-01-10 14:37
Mine seem to have started working on their own... It took a few hours, but Homebridge seems to connected to both now. I've tested and they're both working. But, I've not restarted Homebridge to test, as I'm concerned that this will cause the same issue to happen again.

**Comment by devbobo** [comment] 2017-05-05 00:24
There haven't been any reports in a few months, so I'm closing this issue.

**Closed by devbobo** 2017-05-05 00:24 UTC

**Comment by erfinb** [comment] 2017-05-05 00:27
This issue shouldn't be closed it is still a problem that has not been resolved.

**Comment by devbobo** [comment] 2017-05-05 00:29
@erfinb you're welcome to dive into the code and fix it...just saying

**Comment by erfinb** [comment] 2017-05-05 00:37
Or we can wait to see when we get resolution...just saying.

**Comment by timothy-gibson** [comment] 2019-01-13 02:18
Hi all, I'm still encountering this problem - did anyone end up working out a fix? I've found that if I open up the Wemo App and force a refresh of the devices, the correct statuses are then propogated to homebridge. Is it possible to do this periodically using this plugin?

Node Version: v8.15.0
Homebridge Version: 0.4.45
homebridge-platform-wemo Version: 1.3.8

Running one wemo link with multiple bulbs and homebridge running on a Raspberry Pi 2.
