### ISSUE TITLE
Cannot read property UDN of NULL

### ISSUE THREAD

**Issue by Mustavo** [rudders/homebridge-platform-wemo#100] opened 2017-06-10 13:49 UTC
Hello, 

Everything has been going very well in my setup, but suddenly today I start getting this error after adding my 4th WeMo device. If you have any experience with it, or tips on how I can overcome I would really appreciate hearing about them:

/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:102
        var uuid = UUIDGen.generate(device.UDN);
                                          ^

TypeError: Cannot read property 'UDN' of null
    at addDiscoveredDevice (/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:102:43)
    at /usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/index.js:54:12
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:79:5)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)****

**Comment by devbobo** [comment] 2017-06-10 23:58
what device was added ?

**Comment by DMBlakeley** [comment] 2017-06-21 17:34
I am receiving the same error which occurs randomly.  Looked back through the log file to see if there was a consistent Wemo device that was being accessed before the error but no luck.  Have a suspicion that a Netcam is the cause (I have 2).  I have listed both addresses as ignored devices ("ignoredDevices": ["EC1A5957B190", "EC1A59E65DD0"]), however, both are added as devices when Homebridge starts up and show up in the Home app.

**Comment by DMBlakeley** [comment] 2017-06-22 19:26
I had swapped a couple of the Wemo switches and noticed that although they seemed to operated correctly via HomeKit the homebridge log identified them as incorrect.  I stopped homebridge, renamed the cachedAccessories list, and restarted homebride which created a new cachedAccessories list.  I have not had a reboot since.

**Comment by DMBlakeley** [comment] 2017-06-24 02:48
I am still struggling with this error.  I am pretty sure that it is associated with the 2 NetCams that I have installed.  EC1A5957B190 is a "NetCamHDv1" while EC1A59E65DD0 is a "NetCam HDv2".  If I unplug the NetCams the error will stop.  If I then stop homebridge, plug them back in, the error will seem to go away.  I have also noted that adding EC1A5957B190 to the ignoredDevices entry does not fully remove the device while adding EC1A59E65DD0 removes the device.

Any advise would be appreciated.

**Comment by devbobo** [comment] 2017-06-25 04:25
I've just released a new version (`1.3.1`) when should prevent the error described in the OP.

Please ensure that you are also running the most recent version of `wemo-client` which should be `0.13.0`

**Comment by DMBlakeley** [comment] 2017-06-25 19:15
Thanks for releasing the new version.  Installed this morning and there have been no UDN of 'nul' issues since.  Will continue to monitor log over next few days.

**Comment by devbobo** [comment] 2017-06-27 02:49
Closing, reopen if any issues pop up.

**Closed by devbobo** 2017-06-27 02:49 UTC
